-- ============================================
-- Mock Job Data for DataJobPortal
-- ============================================
-- This file contains sample job data for testing
-- Run this after SUPABASE_SETUP.sql or independently
-- ============================================

-- Clear existing test data (optional - uncomment if needed)
-- DELETE FROM jobs WHERE posted_by = 'admin';

-- Insert comprehensive mock job data
INSERT INTO jobs (company, title, location, salary, company_logo, tags, link, description, work_location, experience, working_schedule, employment_type, posted_by, created_at)
VALUES 
  -- Recent jobs (last 24 hours)
  (
    'Amazon',
    'Senior Data Engineer',
    'San Francisco, CA',
    '$125k-180k/year',
    'A',
    ARRAY['Full time', 'Senior level', 'Remote', 'Project work'],
    'https://www.amazon.jobs/en/jobs/123456',
    'We are looking for an experienced Data Engineer to design and build scalable data pipelines. You will work with large-scale distributed systems and collaborate with cross-functional teams.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '2 hours'
  ),
  (
    'Google',
    'Junior Data Analyst',
    'Mountain View, CA',
    '$90k-120k/year',
    'G',
    ARRAY['Full time', 'Junior level', 'Remote', 'Project work', 'Flexible schedule'],
    'https://careers.google.com/jobs/123456',
    'Entry-level position for data analysis. Perfect for recent graduates interested in working with big data and analytics tools.',
    'Remote',
    'Junior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '5 hours'
  ),
  (
    'Microsoft',
    'Senior Data Scientist',
    'Seattle, WA',
    '$140k-200k/year',
    'M',
    ARRAY['Full time', 'Senior level', 'Full Day'],
    'https://careers.microsoft.com/jobs/123456',
    'Senior role in data science and machine learning. Lead ML projects and mentor junior data scientists.',
    'On-site',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '8 hours'
  ),
  (
    'Meta',
    'Data Analyst',
    'Menlo Park, CA',
    '$110k-150k/year',
    'f',
    ARRAY['Full time', 'Middle level', 'Remote', 'Project work'],
    'https://www.metacareers.com/jobs/123456',
    'Analyze user behavior data and provide insights to product teams. Work with SQL, Python, and data visualization tools.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '12 hours'
  ),
  (
    'Netflix',
    'Data Engineer',
    'Los Gatos, CA',
    '$130k-180k/year',
    'N',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://jobs.netflix.com/jobs/123456',
    'Build and maintain data infrastructure for content analytics. Experience with Spark, Airflow, and cloud platforms required.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '18 hours'
  ),
  -- Jobs from last week
  (
    'Apple',
    'Data Architect',
    'Cupertino, CA',
    '$150k-220k/year',
    '🍎',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://jobs.apple.com/jobs/123456',
    'Design and implement data architecture solutions. Lead technical decisions and work with engineering teams.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '2 days'
  ),
  (
    'Tesla',
    'Machine Learning Engineer',
    'Palo Alto, CA',
    '$135k-190k/year',
    'T',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://www.tesla.com/careers/jobs/123456',
    'Develop ML models for autonomous driving and energy optimization. Strong background in deep learning required.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '3 days'
  ),
  (
    'IBM',
    'Business Intelligence Analyst',
    'Armonk, NY',
    '$100k-140k/year',
    'IBM',
    ARRAY['Full time', 'Middle level', 'Remote', 'Flexible schedule'],
    'https://www.ibm.com/careers/jobs/123456',
    'Create dashboards and reports for business stakeholders. Experience with Tableau, Power BI, or similar tools.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '4 days'
  ),
  (
    'Oracle',
    'Database Administrator',
    'Austin, TX',
    '$120k-160k/year',
    'O',
    ARRAY['Full time', 'Senior level', 'Full Day'],
    'https://www.oracle.com/careers/jobs/123456',
    'Manage and optimize Oracle databases. Ensure high availability and performance of database systems.',
    'On-site',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '5 days'
  ),
  (
    'Salesforce',
    'Data Scientist',
    'San Francisco, CA',
    '$130k-180k/year',
    'S',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://www.salesforce.com/careers/jobs/123456',
    'Apply statistical methods and machine learning to solve business problems. Work with large datasets and cloud platforms.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '6 days'
  ),
  (
    'Spotify',
    'Data Engineer',
    'New York, NY',
    '$125k-170k/year',
    'S',
    ARRAY['Full time', 'Middle level', 'Remote', 'Flexible schedule'],
    'https://www.lifeatspotify.com/jobs/123456',
    'Build data pipelines for music analytics. Work with real-time streaming data and batch processing systems.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '7 days'
  ),
  (
    'Uber',
    'Senior Data Analyst',
    'San Francisco, CA',
    '$115k-160k/year',
    'U',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://www.uber.com/careers/jobs/123456',
    'Analyze ride-sharing data to improve operations. Create reports and dashboards for business intelligence.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '8 days'
  ),
  (
    'Airbnb',
    'Data Engineer',
    'San Francisco, CA',
    '$130k-180k/year',
    'A',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://careers.airbnb.com/jobs/123456',
    'Design and maintain data infrastructure for marketplace analytics. Experience with distributed systems required.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '9 days'
  ),
  (
    'LinkedIn',
    'Data Scientist',
    'Sunnyvale, CA',
    '$140k-200k/year',
    'L',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://www.linkedin.com/jobs/view/123456',
    'Develop ML models for recommendation systems. Work with large-scale data and production systems.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '10 days'
  ),
  (
    'Twitter',
    'Data Analyst',
    'San Francisco, CA',
    '$105k-145k/year',
    'T',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://careers.twitter.com/jobs/123456',
    'Analyze social media data and user engagement metrics. Create insights for product and engineering teams.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '11 days'
  ),
  (
    'Adobe',
    'Machine Learning Engineer',
    'San Jose, CA',
    '$135k-190k/year',
    'A',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://www.adobe.com/careers/jobs/123456',
    'Build ML models for creative tools and marketing platforms. Experience with computer vision and NLP preferred.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '12 days'
  ),
  (
    'Intel',
    'Data Architect',
    'Santa Clara, CA',
    '$145k-210k/year',
    'I',
    ARRAY['Full time', 'Senior level', 'On-site'],
    'https://www.intel.com/careers/jobs/123456',
    'Design data architecture for semiconductor manufacturing. Lead data strategy and technical architecture decisions.',
    'On-site',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '13 days'
  ),
  (
    'NVIDIA',
    'Data Scientist',
    'Santa Clara, CA',
    '$140k-200k/year',
    'N',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://www.nvidia.com/careers/jobs/123456',
    'Apply deep learning and AI to solve complex problems. Work with GPU computing and large-scale neural networks.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '14 days'
  ),
  (
    'Palantir',
    'Data Engineer',
    'Denver, CO',
    '$130k-180k/year',
    'P',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://www.palantir.com/careers/jobs/123456',
    'Build data platforms for government and enterprise clients. Work with sensitive data and security requirements.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '15 days'
  ),
  (
    'Databricks',
    'Senior Data Engineer',
    'San Francisco, CA',
    '$145k-210k/year',
    'D',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://www.databricks.com/careers/jobs/123456',
    'Build data engineering solutions using Apache Spark. Help customers implement modern data architectures.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '16 days'
  ),
  (
    'Snowflake',
    'Data Engineer',
    'San Mateo, CA',
    '$135k-185k/year',
    'S',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://careers.snowflake.com/jobs/123456',
    'Design and implement data solutions using Snowflake platform. Work with cloud data warehousing technologies.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '17 days'
  ),
  (
    'Stripe',
    'Data Analyst',
    'San Francisco, CA',
    '$110k-150k/year',
    'S',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://stripe.com/jobs/123456',
    'Analyze payment and financial data. Create insights to improve product and business operations.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '18 days'
  ),
  (
    'Coinbase',
    'Data Scientist',
    'San Francisco, CA',
    '$135k-190k/year',
    'C',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://www.coinbase.com/careers/jobs/123456',
    'Apply ML to cryptocurrency and blockchain data. Build models for fraud detection and trading insights.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '19 days'
  ),
  (
    'Zoom',
    'Data Engineer',
    'San Jose, CA',
    '$125k-170k/year',
    'Z',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://zoom.us/careers/jobs/123456',
    'Build data infrastructure for video conferencing analytics. Work with real-time streaming and batch data.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '20 days'
  ),
  (
    'Shopify',
    'Data Analyst',
    'Ottawa, ON',
    '$100k-140k/year',
    'S',
    ARRAY['Full time', 'Middle level', 'Remote', 'Flexible schedule'],
    'https://www.shopify.com/careers/jobs/123456',
    'Analyze e-commerce data to help merchants succeed. Create dashboards and reports for business intelligence.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '21 days'
  ),
  (
    'Reddit',
    'Data Scientist',
    'San Francisco, CA',
    '$130k-180k/year',
    'R',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://www.redditinc.com/careers/jobs/123456',
    'Apply ML to improve content recommendations and user experience. Work with large-scale social media data.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '22 days'
  ),
  (
    'Pinterest',
    'Machine Learning Engineer',
    'San Francisco, CA',
    '$140k-200k/year',
    'P',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://www.pinterestcareers.com/jobs/123456',
    'Build recommendation systems and ML models for visual discovery. Experience with computer vision preferred.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '23 days'
  ),
  (
    'Snapchat',
    'Data Engineer',
    'Santa Monica, CA',
    '$125k-175k/year',
    'S',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://www.snap.com/careers/jobs/123456',
    'Build data pipelines for social media analytics. Work with real-time data and large-scale systems.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '24 days'
  ),
  (
    'TikTok',
    'Data Scientist',
    'Los Angeles, CA',
    '$135k-190k/year',
    'T',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://careers.tiktok.com/jobs/123456',
    'Develop ML models for video recommendation and content understanding. Work with massive-scale data.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '25 days'
  ),
  (
    'GitHub',
    'Data Analyst',
    'San Francisco, CA',
    '$110k-150k/year',
    'G',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://github.com/careers/jobs/123456',
    'Analyze developer activity and platform usage data. Create insights to improve developer experience.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '26 days'
  ),
  (
    'MongoDB',
    'Data Engineer',
    'New York, NY',
    '$130k-180k/year',
    'M',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://www.mongodb.com/careers/jobs/123456',
    'Build data infrastructure using MongoDB and modern data stack. Design scalable data architectures.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '27 days'
  ),
  (
    'Elastic',
    'Data Scientist',
    'Mountain View, CA',
    '$135k-190k/year',
    'E',
    ARRAY['Full time', 'Senior level', 'Remote'],
    'https://www.elastic.co/careers/jobs/123456',
    'Apply ML to search and analytics platforms. Work with Elasticsearch and large-scale data systems.',
    'Remote',
    'Senior',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '28 days'
  ),
  (
    'Atlassian',
    'Data Analyst',
    'San Francisco, CA',
    '$105k-145k/year',
    'A',
    ARRAY['Full time', 'Middle level', 'Remote', 'Flexible schedule'],
    'https://www.atlassian.com/careers/jobs/123456',
    'Analyze product usage data for Jira and Confluence. Create insights to improve team collaboration tools.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '29 days'
  ),
  (
    'Slack',
    'Data Engineer',
    'San Francisco, CA',
    '$130k-180k/year',
    'S',
    ARRAY['Full time', 'Middle level', 'Remote'],
    'https://slack.com/careers/jobs/123456',
    'Build data infrastructure for workplace communication analytics. Work with real-time messaging data.',
    'Remote',
    'Middle',
    'Full time',
    'Full Day',
    'admin',
    NOW() - INTERVAL '30 days'
  )
ON CONFLICT DO NOTHING;

-- Verify data was inserted
SELECT 
  COUNT(*) as total_jobs,
  COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '24 hours') as jobs_last_24h,
  COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '7 days') as jobs_last_7d,
  COUNT(DISTINCT company) as unique_companies
FROM jobs;
